apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${K8_DEPLOYMENT}
  namespace: ${K8_NAMESPACE}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${K8_APP}
  template:
    metadata:
      labels:
        app: ${K8_APP}
    spec:
      containers:
        - name: ${SERVICE_NAME}
          image: ${DOCKER_USERNAME}/property_manager.${SERVICE_NAME}:${DOCKER_IMAGE_TAG}
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: ${K8_SECRET}
