apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: ${K8_NAMESPACE}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/var/lib/mongodb"
