apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${K8_NAMESPACE}
spec:
  type: ClusterIP
  selector:
    app: ${K8_APP}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
